### ISSUE TITLE
Multiple tracking IDs?

### ISSUE THREAD

**Issue by timodenissen** [DaSchTour/matomo-mediawiki-extension#23]
Is it possible to add more than one ID to $wgPiwikIDSite? I want to track with two IDs instead of one.

**Comment by Seb35** [comment]
Sorry about the delay. Do you mean you want to track a single MediaWiki wiki in two (or more) Matomo? With the same $wgMatomoURL or with different ones?

**Comment by univentionit** [comment]
Correct, multiple $wgPiwikIDSite to one $wgMatomoURL. I tried adding $wgPiwikIDSite multiple times but only the lsat entry is evaluated. (eg. I want to track to ID 1 and 10, but only 10 is tracked).

**Comment by timodenissen** [comment]
Correct, multiple $wgPiwikIDSite to one $wgMatomoURL. I tried adding $wgPiwikIDSite multiple times but only the lsat entry is evaluated. (eg. I want to track to ID 1 and 10, but only 10 is tracked).

**Comment by YOUR1** [comment]
Tracking multiple site ids is not possible in Matomo's tracking client. See: https://developer.matomo.org/api-reference/tracking-javascript. I don't think this is a good feature to add.

**Comment by timodenissen** [comment]
Thanks for the update here. I think, for the time being, this issue can be closed.
