### ISSUE TITLE
Mismatch between documentation and default config setting: wgMatomoIgnoreSysops

### ISSUE THREAD

**Issue by otheus** [DaSchTour/matomo-mediawiki-extension#29]
The README file suggests that `$wgMatomoIgnoreSysops` defaults to `false` and could be set to `true` to ignore actions by sysops. However, the `extension.json` file sets this to `true` by default.

**Comment by Seb35** [comment]
Fixed in c75666d as well as the same documentation issue for bots. Thanks @otheus!
