### ISSUE TITLE
matomo dont work

### ISSUE THREAD

**Issue by mabed-fr** [DaSchTour/matomo-mediawiki-extension#30]
Hello,
I just built a wiki with mediawiki (docker) and a matomo (docker) publish on the same network card.

My problem is that I don't get any stats.

I have the impression that the plugin does not give the correct configuration in the matomo pages.

My configurations:

mediawiki Localsetting

# Matomo
wfLoadExtension( 'Matomo' );
$wgPiwikURL = "myfqdn.fr";
$wgMatomoIDSite = "1";

The module is succeful charged because i view it in the code 

But i think i have in error.

Matomo demand to past this :

![stats-code](https://user-images.githubusercontent.com/25350431/79347115-89ca0800-7f33-11ea-9715-fbe949161fdd.png)

and mediawiki plugin past this:

![matomo-inspect-element](https://user-images.githubusercontent.com/25350431/79347010-61daa480-7f33-11ea-9ea2-9a045e984ff4.png)

Thank'you for your ideas

**Comment by SamueloWeb** [comment]
x2 bro, We need Help

**Comment by Goldshop** [comment]
You need to use $wgMatomoURL instead of $wgPiwikURL

**Comment by valerio-bozzolan** [comment]
Hi @mabed-fr, please mark as closed if you think that was the problem :)

**Comment by Seb35** [comment]
The old parameters like $wgPiwikURL should still work (although they should no more be used and should be deprecated to encourage users to update them to $wgMatomo*).

I close the issue since there is no reply to @Goldshop comment. If needed it can be reopen.
