### ISSUE TITLE
I made some progress ..

### ISSUE THREAD

**Issue by gruniversal** [DaSchTour/matomo-mediawiki-extension#31]
Hello there,

I was looking for an extension to add Matomo tracking and an opt out to my MediaWiki project.

After playing around a bit with your extension I decided to make some additional development and came up with this:
https://gitlab.com/gruniversal/erwin/-/tree/master/src/extensions/Matomo

Basically I did the following:
* added parser tag <matomo-optout /> to Matomo extension for matomo opt out
* simplified path handling and allowed for full URLs (backwards compatible)
* restructured matomo callbacks and custom js
* removed unused parameters, did some cleanup and improved code readability

I think this will fix some issues here:
* https://github.com/DaSchTour/matomo-mediawiki-extension/issues/22
* https://github.com/DaSchTour/matomo-mediawiki-extension/issues/27
* https://github.com/DaSchTour/matomo-mediawiki-extension/issues/28
* https://github.com/DaSchTour/matomo-mediawiki-extension/issues/29

I am a bit new to MediaWiki development and I don't want to start another fork, but I found my progress good enough to share it with you. Maybe you can look over my changes and decide, if you want to take them into your repo. Then I could switch back to the official version. This might help other people too.

Best regards,
David

**Comment by DaSchTour** [comment]
@gruniversal can you please add you changes to a github fork and create a Pull-Request

**Comment by Goldshop** [comment]
> @gruniversal can you please add you changes to a github fork and create a Pull-Request

I have created a pull request using the latest version 4.2.4

**Comment by gruniversal** [comment]
Hello there,

it's not completely different but there are 26 separate commits, which I did my best to document here: https://gitlab.com/gruniversal/erwin/-/commits/master/src/extensions/Matomo

The main new feature is a simple opt-out button, which can be inserted as parser tag:
https://gitlab.com/gruniversal/erwin/-/blob/master/src/extensions/Matomo/README.md#matomo-opt-out

As far as I know this version will be fully compatible with the latest one. I also tried to improve code readability and fixed the issues as described above. Last month I removed some functions that are deprecated as of MW 1.35.

I would be glad if someone would approve my work, since I think it is a good step forward.

If I can offer you additional information, please let me know.

**Comment by DaSchTour** [comment]
Yeah, but there is no continuous git history and no diff between the current state and your state. That makes it impossible to actually see the changes. Sorry, I can't help here.

**Comment by Goldshop** [comment]
Hi Both, I have have fixed this and created a new pull request.

**Comment by gruniversal** [comment]
Since my changes are not going into this extension, I decided to rename my version to avoid confusion with the original version. I also did some smaller fixes since last year. Because of the renaming the URL changed a bit and you can find the latest version here: https://gitlab.com/gruniversal/erwin/-/tree/master/src/extensions/MatomoOptOut
