### ISSUE TITLE
New (pre)release after 4.0.1 from 2019?

### ISSUE THREAD

**Issue by je-we** [DaSchTour/matomo-mediawiki-extension#38]
I'm not a programmer and not so familiar with github. I was trying to find out, if there are newer versions available as listed on MediaWiki Extension page of Matomo (https://www.mediawiki.org/wiki/Extension:Matomo). Some months ago I've asked there in the discussion regarding my issue:

Since MediaWiki update from 1.36.2 to 1.37.1 I see on top of my Wiki the following debug messages caused by Matomo extension:
`Use of $wgUser was deprecated in MediaWiki 1.35. [Called from MatomoHooks::MatomoSetup in ***/extensions/matomo/Matomo.hooks.php at line 23] in ***/includes/debug/MWDebug.php on line 375`

`$wgUser reassignment detected [Called from MatomoHooks::MatomoSetup in ***/extensions/matomo/Matomo.hooks.php at line 23] in ***/includes/debug/MWDebug.php on line 375`

Any hint how to avoid or is an extension updated planned? Or is there any newer version available to test?
Thank you!

**Comment by gruniversal** [comment]
I had the same problem and fixed it by myself in my own version:
https://gitlab.com/gruniversal/erwin/-/tree/master/src/extensions/MatomoOptOut

It is part of a greater project, but the extension should also work stand alone and I regard it as fully compatible to the official version 4.0.1.

If you are bold enough, you can try and download it here:
https://gitlab.com/gruniversal/erwin/-/archive/master/erwin-master.zip?path=src/extensions/MatomoOptOut

No guarantees! Not tested in MW 1.36 or MW 1.37 so far!

See also: #31

**Comment by je-we** [comment]
I was bold enough ;-) and copied your extension, did settings in LocalSettings.php (can see it in Special:Version) but cannot see any count in Matomo after 1 day.

**Comment by gruniversal** [comment]
@je-we Since Github does not seem to have a DM feature, please write your website and maybe further information to gruniversal@gmx.de so I can take a closer look (and we don't spam here).

**Comment by squirrelslair** [comment]
I added a pull request that should fix this.

**Comment by Seb35** [comment]
I just issued a [new version 5.0.0](https://github.com/DaSchTour/matomo-mediawiki-extension/releases/tag/v5.0.0) with two main maintenance fix (whose $wgUser) and it is available on [Packagist](https://packagist.org/packages/mediawiki/matomo).

@gruniversal: I deleted the initial version of [your comment above](https://github.com/DaSchTour/matomo-mediawiki-extension/issues/38#issuecomment-1113967326) containing your email address, so that it is no more available in the history of the comment.
