### ISSUE TITLE
Matomo extension calls a function deprecated in MediaWiki 1.36

### ISSUE THREAD

**Issue by felipeforte** [DaSchTour/matomo-mediawiki-extension#39]
When setting the parameter `$wgMatomoTrackUsernames = true;`, MediaWiki reports:

> **Deprecated**:  Use of User::isLoggedIn was deprecated in MediaWiki 1.36. [Called from MediaWiki\Extension\Matomo\Hooks::addMatomo in /mediawiki/extensions/Matomo/src/Hooks.php at line 173] in **/mediawiki/includes/debug/MWDebug.php** on line **375**

MediaWiki 1.36's Release notes mention this:

> The confusingly-named User->isLoggedIn() method has been deprecated in favour of the method it wraps, User->isRegistered().

I confirmed that renaming the functions fixes the issue

**Comment by Seb35** [comment]
Fixed by #40. Thanks @felipeforte!
